Bumping up dependencies
LechevSpace/embedded-canvas pull request #11
Opened 2023-10-31 23:22 UTC by dawid-nowak

Bumping up dependencies to ensure that it works with Raspberry PI and Pimoroni Enviro mini board

2023-11-01 15:19 UTC, elpiel commented
Thank you for the contribution.
I can release a new minor version as soon as the checks pass.

If you have example of how you use the crate I would love to see it.

2023-11-01 15:27 UTC, elpiel requested changes

2023-11-01 15:27 UTC, elpiel commented on Cargo.toml
>  embedded-graphics-simulator = "0.3"
- [ ] You should also update the simulator to version `0.5` as examples are failing.

2023-11-05 18:13 UTC, elpiel commented on Cargo.toml
>  embedded-graphics-simulator = "0.3"
```suggestion
embedded-graphics-simulator = "0.5"
```

2023-11-06 08:11 UTC, merged

2023-11-06 08:11 UTC, elpiel commented
Thank you once again for your contribution!
I will fix the MSRV before releasing

2023-11-08 18:33 UTC, dawid-nowak commented
Super, thank you. The project is here https://github.com/dawid-nowak/all_in_one_enviro_mini_rs. Your library greatly helped to make it much better looking :)

2023-11-09 08:30 UTC, elpiel commented
Great to hear that and thank you for sharing your project.
I was keen to see how you're using the crate.

Btw is there are reason you manually go over the pixel and drawing them on the display here?
You could use the `canvas.draw(disp)` directly iirc

https://github.com/dawid-nowak/all_in_one_enviro_mini_rs/blob/bf87fdee6c7631dadbed096911100356e1fd7664/src/display.rs#L100-L102

2023-11-10 12:14 UTC, dawid-nowak commented
Yeah, draw uses ```target.draw_iter(pixels_iter)``` which turned out to be much slower than ```disp.fill_contiguous(&bb, pixels_iter)```

2023-11-10 13:12 UTC, elpiel commented
Hmm... Ok, that's great to know, I can make some tests and benchmark the result to improve the speed. I opened  #13 for this.
Thanks!

2023-11-10 16:08 UTC, dawid-nowak commented
I don't think it is the problem with canvas but more with a display driver which implements DrawTarget trait.  For example, this driver only implements ```draw_iter``` which only updates the [buffer]( https://github.com/wjakobczyk/st7920/blob/e0518c54af26c352ebf912a49099f00cf915d4d0/src/lib.rs#L460) and one still needs to flush the buffer to send the data to the [display](https://github.com/wjakobczyk/st7920/blob/e0518c54af26c352ebf912a49099f00cf915d4d0/examples/graphics.rs#L72). 
Happy to chat on discord ```dawid.nowak``` if you want to discuss further.